# Generated by Django 5.0 on 2024-03-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
