# Generated by Django 5.0 on 2024-03-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customuser_options_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
