# Generated by Django 5.0 on 2024-03-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
